/*O Exercício 11.3 pediu ao leitor que escrevesse uma série de instruções simples. Na realidade, essas instruções formam o núcleo de um tipo importante de programa de processamento de arquivos, que é um programa de correspondência de arquivos. No processamento comercial, é comum haver vários arquivos em cada sistema. Em um sistema contábil de contas a receber, por exemplo, geralmente há um arquivo-mestre contendo informações detalhadas sobre cada cliente como seu nome, endereço, número do telefone, saldo a pagar limite de crédito, condições de desconto, cláusulas de contratos e possivelmente um histórico condensado de compras e pagamentos recentes.
À medida que as transações ocorrem (i.e., são feitas compras e realizados pagamentos na
conta), elas são registradas no arquivo. Ao final de cada período comercial (i.e., um mês para algumas companhias, uma semana para outras, um dia em ainda outros casos) o arquivo de
transações (chamado " trans . dat" no Exercício 11.3) é aplicado ao arquivo-mestre (chamado "oldmast.dat" no Exercício 11.3), atualizando assim o registro de pagamentos e compras de cada conta. Depois de cada uma dessas atualizações ser realizada, o arquivo-mestre é gravado novamente como um novo arquivo (" newmast. dat"), que então é usado no final do próximo período comercial para iniciar mais uma vez o processo de atualização.
Os programas de correspondência de arquivos devem lidar com determinados problemas que
não existem em programas de arquivos simples. Por exemplo, nem sempre ocorre uma correspondência. Um cliente em um arquivo-mestre pode não ter feito nenhuma compra ou nenhum pagamento no período comercial atual e portanto não aparecerá no arquivo de transação nenhum registro para esse cliente. Similarmente, um cliente que fez algumas compras ou alguns pagamentos pode ter acabado de se mudar para essa comunidade e a companhia ainda não teve a oportunidade de criar um registro-mestre para esse cliente.
Use as instruções escritas no Exercício 11.3 como base para escrever um programa completo
de correspondência de arquivos de contas a receber. Use o número da conta em cada arquivo como campo-chave dos registros para as correspondências. Assuma que cada arquivo é um arquivo seqüencial com registros armazenados na ordem crescente do número de contas.
Quando acontecer uma correspondência (i.e., quando aparecerem registros com o mesmo
número de conta tanto no arquivo-mestre como no arquivo de transações), adicione ao saldo atual no arquivo-mestre a quantia em reais do arquivo de transações e grave o arquivo " newmast. dat". (Suponha que as compras são indicadas por quantias positivas no arquivo de transações e os pagamentos são indicados por quantias negativas.) Quando houver um registro-mestre de uma determinada conta, mas não houver registro de transação correspondente, simplesmente grave o registro-mestre em " newmast. dat". Quando houver uma transação mas não houver um registromestre, imprima a mensagem "Nao ha correspondência entre o registro de transação e o numero da conta ..." (preencha o número da conta do registro da transação).*/